name:                diaryvpn
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- DisambiguateRecordFields
- NamedFieldPuns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Werror

library:
  source-dirs: src
  dependencies:
    - text
    - bytestring
    - http-types

executables:
  diaryvpn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diaryvpn
    - wai
    - warp
    - stm
    - bytestring
    - wai-extra
    - time

tests:
  diaryvpn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diaryvpn
    - tasty
    - tasty-hunit
    - text
    - bytestring
    - http-types
    - hedgehog
    - tasty-hedgehog
