name: backend
version: 0.1.0.0

dependencies:
- base
- scotty

default-extensions:
- OverloadedStrings

ghc-options:
- -Werror
- -Weverything
- -Wno-safe
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-unsafe
- -Wno-all-missed-specialisations
- -Wno-missing-kind-signatures

executables:
  backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
