name:                backend
version:             0.1.0.0

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- DuplicateRecordFields

dependencies:
- base

ghc-options:
- -Weverything
- -Werror
- -Wno-missing-kind-signatures
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-missing-deriving-strategies
- -Wno-unsafe
- -Wno-monomorphism-restriction
- -Wno-prepositive-qualified-module
- -Wno-missing-import-lists

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
    - stm
    - bytestring
    - http-types
    - binary
    - wai

library:
  source-dirs: src
  dependencies:
  - bytestring
  - http-types
  - wai
  - text
  - binary
  - stm
  - attoparsec
  - time

tests:
  ded-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
    - tasty-hunit
    - tasty
