name:                backend
version:             0.1.0.0

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

dependencies:
- base

ghc-options:
- -Weverything
- -Werror
- -Wno-missing-kind-signatures
- -Wno-missing-safe-haskell-mode
- -Wno-safe

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
    - stm
    - bytestring

library:
  source-dirs: src
  dependencies:
  - bytestring

tests:
  ded-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
    - tasty-hunit
    - tasty
